GET http://localhost:3000/articles
###
GET http://localhost:3000/articles/categories/280

###
GET http://localhost:3000/articles/6

###
POST http://localhost:3000/articles HTTP/1.1
Content-Type: application/json

{
    "title": "New Article",
    "content": "This is a new article.",
    "image": "https://example.com/image.jpg",
    "categories":[1,2]
}

###
PATCH http://localhost:3000/articles
Content-Type: application/json

{
    "id": 325,
    "title": "Updated Article",
    "content": "This article has been updated.",
    "image": "https://example.com/new-image.jpg",
    "published": true
}



###
DELETE  http://localhost:3000/articles/325

