


GET http://localhost:3000/commentaires
###
GET http://localhost:3000/commentaires/1

###
POST http://localhost:3000/commentaires
Content-Type: application/json

{
    "content": "content du commentaire",
    "articleId":231
}


###
PATCH http://localhost:3000/commentaires
Content-Type: application/json

{   
    "id":2045,
    "content": "Updated content du commentaire"
}


###
DELETE  http://localhost:3000/commentaires/2045